<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Monthly Report</title>
    <style>
        @font-face {
            font-family: 'Koh Santepheap';
            src: url("{!! storage_path('fonts/KohSantepheap-Regular.ttf') !!}") format('truetype');
            font-weight: normal;
            font-style: normal;
        }
        @font-face {
            font-family: 'Koh Santepheap';
            src: url("{!! storage_path('fonts/KohSantepheap-Bold.ttf') !!}") format('truetype');
            font-weight: bold;
            font-style: normal;
        }
        body {
            font-family: 'Koh Santepheap', sans-serif;
            margin: 0;
            padding: 20px;
            font-size: 12px;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 1px solid #ddd;
            padding-bottom: 10px;
        }
        .header h1 {
            margin: 0;
            color: #333;
            font-size: 24px;
        }
        .header p {
            margin: 5px 0;
            color: #666;
            font-size: 14px;
        }
        .summary-box {
            background-color: #f9f9f9;
            border: 1px solid #ddd;
            padding: 15px;
            margin-bottom: 20px;
            border-radius: 5px;
        }
        .summary-title {
            font-weight: bold;
            font-size: 16px;
            margin-bottom: 10px;
            border-bottom: 1px solid #ddd;
            padding-bottom: 5px;
        }
        .summary-row {
            display: flex;
            justify-content: space-between;
            margin-bottom: 5px;
        }
        .summary-label {
            font-weight: bold;
            width: 150px;
        }
        .summary-value {
            text-align: right;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        table, th, td {
            border: 1px solid #ddd;
        }
        th {
            background-color: #f2f2f2;
            padding: 8px;
            text-align: left;
            font-weight: bold;
        }
        td {
            padding: 8px;
            vertical-align: top;
        }
        .month-header {
            background-color: #e2efda;
            font-weight: bold;
            font-size: 16px;
            padding: 10px;
            margin-top: 20px;
            margin-bottom: 10px;
            border-radius: 5px;
        }
        .status-paid {
            color: green;
        }
        .status-overdue {
            color: red;
        }
        .status-pending {
            color: orange;
        }
        .footer {
            text-align: center;
            margin-top: 30px;
            font-size: 10px;
            color: #666;
            border-top: 1px solid #ddd;
            padding-top: 10px;
        }
        .page-break {
            page-break-after: always;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Monthly Payment Report</h1>
        <p>Period: {{ $summary['start_date'] }} to {{ $summary['end_date'] }}</p>
        <p>Generated by: {{ $exported_by }} on {{ $exported_at }}</p>
    </div>
    
    <div class="summary-box">
        <div class="summary-title">Summary</div>
        <div class="summary-row">
            <span class="summary-label">Total Amount:</span>
            <span class="summary-value">${{ number_format($summary['total_amount'], 2) }}</span>
        </div>
        <div class="summary-row">
            <span class="summary-label">Total Paid:</span>
            <span class="summary-value">${{ number_format($summary['total_paid'], 2) }}</span>
        </div>
        <div class="summary-row">
            <span class="summary-label">Total Overdue:</span>
            <span class="summary-value status-overdue">${{ number_format($summary['total_overdue'], 2) }}</span>
        </div>
        <div class="summary-row">
            <span class="summary-label">Total Pending:</span>
            <span class="summary-value">${{ number_format($summary['total_pending'], 2) }}</span>
        </div>
        <div class="summary-row">
            <span class="summary-label">Total Payments:</span>
            <span class="summary-value">{{ $summary['payment_count'] }}</span>
        </div>
    </div>
    
    <div class="summary-title">Monthly Breakdown</div>
    <table>
        <thead>
            <tr>
                <th>Month</th>
                <th>Total Amount</th>
                <th>Paid</th>
                <th>Overdue</th>
                <th>Pending</th>
            </tr>
        </thead>
        <tbody>
            @foreach($monthly_data as $month => $data)
            <tr>
                <td>{{ $data['month_name'] }}</td>
                <td>${{ number_format($data['total_amount'], 2) }}</td>
                <td class="status-paid">${{ number_format($data['total_paid'], 2) }}</td>
                <td class="status-overdue">${{ number_format($data['total_overdue'], 2) }}</td>
                <td>${{ number_format($data['total_pending'], 2) }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
    
    <div class="page-break"></div>
    
    @foreach($monthly_data as $month => $data)
    <div class="month-header">{{ $data['month_name'] }}</div>
    
    <table>
        <thead>
            <tr>
                <th>Contract ID</th>
                <th>Step</th>
                <th>Description</th>
                <th>Amount</th>
                <th>Due Date</th>
                <th>Status</th>
                <th>Buyer</th>
                <th>Land Plot</th>
            </tr>
        </thead>
        <tbody>
            @foreach($data['payment_steps'] as $step)
            <tr>
                <td>{{ $step['contract_id'] }}</td>
                <td>{{ $step['step_number'] }}</td>
                <td>{{ $step['payment_description'] }}</td>
                <td>${{ number_format($step['amount'], 2) }}</td>
                <td>{{ $step['due_date'] }}</td>
                <td class="status-{{ strtolower($step['status']) }}">{{ ucfirst($step['status']) }}</td>
                <td>{{ $step['buyer_name'] }}</td>
                <td>{{ $step['land_info']['plot_number'] }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
    
    <div class="summary-box">
        <div class="summary-row">
            <span class="summary-label">Month Total:</span>
            <span class="summary-value">${{ number_format($data['total_amount'], 2) }}</span>
        </div>
        <div class="summary-row">
            <span class="summary-label">Month Paid:</span>
            <span class="summary-value">${{ number_format($data['total_paid'], 2) }}</span>
        </div>
        <div class="summary-row">
            <span class="summary-label">Month Overdue:</span>
            <span class="summary-value">${{ number_format($data['total_overdue'], 2) }}</span>
        </div>
    </div>
    
    @if(!$loop->last)
    <div class="page-break"></div>
    @endif
    @endforeach
    
    <div class="footer">
        <p>ONC Land Purchase Tracking System &copy; {{ date('Y') }}</p>
    </div>
</body>
</html>
